Importing the Essential Libraries

In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Analysing the Dataset and Preprocessing the data

In [42]:
dataset = pd.read_csv("CarPrice_Assignment.csv")
print("Shape of the dataset:",dataset.shape)

Shape of the dataset: (205, 26)


In [43]:
dataset['fueltype'].value_counts()

gas       185
diesel     20
Name: fueltype, dtype: int64

In [44]:
dataset.replace({'fueltype':{'gas':1,'diesel':0}}, inplace=True)

In [45]:
dataset['aspiration'].value_counts()

std      168
turbo     37
Name: aspiration, dtype: int64

In [46]:
dataset.replace({'aspiration':{'std':0,'turbo':1}}, inplace=True)

In [47]:
dataset['doornumber'].value_counts()

four    115
two      90
Name: doornumber, dtype: int64

In [48]:
dataset.replace({'doornumber':{'four':4,'two':2}}, inplace=True)

In [49]:
dataset['carbody'].value_counts()

sedan          96
hatchback      70
wagon          25
hardtop         8
convertible     6
Name: carbody, dtype: int64

In [50]:
dataset.replace({'carbody':{'sedan':0,'hatchback':1,'wagon':2,'hardtop':3,'convertible':4}}, inplace=True)

In [51]:
dataset['drivewheel'].value_counts()

fwd    120
rwd     76
4wd      9
Name: drivewheel, dtype: int64

In [52]:
dataset.replace({'drivewheel':{'fwd':0,'rwd':1,'4wd':2}}, inplace=True)

In [53]:
dataset['enginelocation'].value_counts()

front    202
rear       3
Name: enginelocation, dtype: int64

In [54]:
dataset.replace({'enginelocation':{'front':0,'rear':1}}, inplace=True)

In [55]:
dataset['enginetype'].value_counts()

ohc      148
ohcf      15
ohcv      13
dohc      12
l         12
rotor      4
dohcv      1
Name: enginetype, dtype: int64

In [56]:
dataset.replace({'enginetype':{'ohc':0,'ohcf':1,'ohcv':2,'dohc':3,'l':4,'rotor':5,'dohcv':6}}, inplace=True)

In [57]:
dataset['cylindernumber'].value_counts()

four      159
six        24
five       11
eight       5
two         4
three       1
twelve      1
Name: cylindernumber, dtype: int64

In [58]:
dataset.replace({'cylindernumber':{'four':4,'six':6,'five':5,'eight':8,'two':2,'three':3,'twelve':12}}, inplace=True)

In [59]:
dataset['fuelsystem'].value_counts()

mpfi    94
2bbl    66
idi     20
1bbl    11
spdi     9
4bbl     3
mfi      1
spfi     1
Name: fuelsystem, dtype: int64

In [60]:
dataset.replace({'fuelsystem':{'mpfi':0,'2bbl':1,'idi':2,'1bbl':3,'spdi':4,'4bbl':5,'mfi':6,'spfi':7}}, inplace=True)

Viewing the Preprocessed Dataset

In [61]:
dataset.head()

car_ID  symboling                   CarName  fueltype  aspiration  \
0       1          3        alfa-romero giulia         1           0   
1       2          3       alfa-romero stelvio         1           0   
2       3          1  alfa-romero Quadrifoglio         1           0   
3       4          2               audi 100 ls         1           0   
4       5          2                audi 100ls         1           0   

   doornumber  carbody  drivewheel  enginelocation  wheelbase  ...  \
0           2        4           1               0       88.6  ...   
1           2        4           1               0       88.6  ...   
2           2        1           1               0       94.5  ...   
3           4        0           0               0       99.8  ...   
4           4        0           2               0       99.4  ...   

   enginesize  fuelsystem  boreratio  stroke  compressionratio  horsepower  \
0         130           0       3.47    2.68               9.0         111   
1         130           0       3.47    2.68               9.0         111   
2         152           0       2.68    3.47               9.0         154   
3         109           0       3.19    3.40              10.0         102   
4         136           0       3.19    3.40               8.0         115   

   peakrpm  citympg  highwaympg    price  
0     5000       21          27  13495.0  
1     5000       21          27  16500.0  
2     5000       19          26  16500.0  
3     5500       24          30  13950.0  
4     5500       18          22  17450.0  

[5 rows x 26 columns]

In [62]:
dataset.describe()

car_ID   symboling    fueltype  aspiration  doornumber     carbody  \
count  205.000000  205.000000  205.000000  205.000000  205.000000  205.000000   
mean   103.000000    0.834146    0.902439    0.180488    3.121951    0.819512   
std     59.322565    1.245307    0.297446    0.385535    0.994966    0.990944   
min      1.000000   -2.000000    0.000000    0.000000    2.000000    0.000000   
25%     52.000000    0.000000    1.000000    0.000000    2.000000    0.000000   
50%    103.000000    1.000000    1.000000    0.000000    4.000000    1.000000   
75%    154.000000    2.000000    1.000000    0.000000    4.000000    1.000000   
max    205.000000    3.000000    1.000000    1.000000    4.000000    4.000000   

       drivewheel  enginelocation   wheelbase   carlength  ...  enginesize  \
count  205.000000      205.000000  205.000000  205.000000  ...  205.000000   
mean     0.458537        0.014634   98.756585  174.049268  ...  126.907317   
std      0.581148        0.120377    6.021776   12.337289  ...   41.642693   
min      0.000000        0.000000   86.600000  141.100000  ...   61.000000   
25%      0.000000        0.000000   94.500000  166.300000  ...   97.000000   
50%      0.000000        0.000000   97.000000  173.200000  ...  120.000000   
75%      1.000000        0.000000  102.400000  183.100000  ...  141.000000   
max      2.000000        1.000000  120.900000  208.100000  ...  326.000000   

       fuelsystem   boreratio      stroke  compressionratio  horsepower  \
count  205.000000  205.000000  205.000000        205.000000  205.000000   
mean     0.990244    3.329756    3.255415         10.142537  104.117073   
std      1.306058    0.270844    0.313597          3.972040   39.544167   
min      0.000000    2.540000    2.070000          7.000000   48.000000   
25%      0.000000    3.150000    3.110000          8.600000   70.000000   
50%      1.000000    3.310000    3.290000          9.000000   95.000000   
75%      1.000000    3.580000    3.410000          9.400000  116.000000   
max      7.000000    3.940000    4.170000         23.000000  288.000000   

           peakrpm     citympg  highwaympg         price  
count   205.000000  205.000000  205.000000    205.000000  
mean   5125.121951   25.219512   30.751220  13276.710571  
std     476.985643    6.542142    6.886443   7988.852332  
min    4150.000000   13.000000   16.000000   5118.000000  
25%    4800.000000   19.000000   25.000000   7788.000000  
50%    5200.000000   24.000000   30.000000  10295.000000  
75%    5500.000000   30.000000   34.000000  16503.000000  
max    6600.000000   49.000000   54.000000  45400.000000  

[8 rows x 25 columns]

Creating the features and dependent variable

In [63]:
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values
y = y.reshape(len(y),1)

In [64]:
X

array([[1.0e+00, 0.0e+00, 2.0e+00, ..., 5.0e+03, 2.1e+01, 2.7e+01],
       [1.0e+00, 0.0e+00, 2.0e+00, ..., 5.0e+03, 2.1e+01, 2.7e+01],
       [1.0e+00, 0.0e+00, 2.0e+00, ..., 5.0e+03, 1.9e+01, 2.6e+01],
       ...,
       [1.0e+00, 0.0e+00, 4.0e+00, ..., 5.5e+03, 1.8e+01, 2.3e+01],
       [0.0e+00, 1.0e+00, 4.0e+00, ..., 4.8e+03, 2.6e+01, 2.7e+01],
       [1.0e+00, 1.0e+00, 4.0e+00, ..., 5.4e+03, 1.9e+01, 2.5e+01]])

In [65]:
y

array([[13495.   ],
       [16500.   ],
       [16500.   ],
       [13950.   ],
       [17450.   ],
       [15250.   ],
       [17710.   ],
       [18920.   ],
       [23875.   ],
       [17859.167],
       [16430.   ],
       [16925.   ],
       [20970.   ],
       [21105.   ],
       [24565.   ],
       [30760.   ],
       [41315.   ],
       [36880.   ],
       [ 5151.   ],
       [ 6295.   ],
       [ 6575.   ],
       [ 5572.   ],
       [ 6377.   ],
       [ 7957.   ],
       [ 6229.   ],
       [ 6692.   ],
       [ 7609.   ],
       [ 8558.   ],
       [ 8921.   ],
       [12964.   ],
       [ 6479.   ],
       [ 6855.   ],
       [ 5399.   ],
       [ 6529.   ],
       [ 7129.   ],
       [ 7295.   ],
       [ 7295.   ],
       [ 7895.   ],
       [ 9095.   ],
       [ 8845.   ],
       [10295.   ],
       [12945.   ],
       [10345.   ],
       [ 6785.   ],
       [ 8916.5  ],
       [ 8916.5  ],
       [11048.   ],
       [32250.   ],
       [35550.   ],
       [36000.   ],


Feature Scaling the Dependent Variables and Features

In [66]:
from sklearn.preprocessing import StandardScaler
scx = StandardScaler()
scy = StandardScaler()

X = scx.fit_transform(X)
y = scy.fit_transform(y)

Splitting the dependent variable and features into training and testing dataset

In [67]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [68]:
X_test

array([[ 3.28797975e-01, -4.69295318e-01, -1.13038833e+00,
         1.82583077e-01, -7.90949943e-01, -1.21866670e-01,
        -9.41654571e-01, -1.21468051e+00, -7.98052621e-01,
         1.53892721e-01, -1.25251243e+00, -5.32820983e-01,
        -3.52886991e-01, -8.64382552e-01,  7.48816868e-03,
        -1.10945866e+00, -3.36969687e-01, -2.88348910e-01,
        -9.15570870e-01, -2.62960216e-01,  8.85740275e-01,
         1.05519283e+00],
       [ 3.28797975e-01, -4.69295318e-01,  8.84651737e-01,
         1.19419202e+00,  9.33994082e-01, -1.21866670e-01,
         9.56109082e-01,  1.11729520e+00,  2.76731186e-01,
         1.53892721e-01,  1.14636922e+00,  1.63727772e+00,
         1.50203181e+00,  8.20699586e-01, -7.60049121e-01,
        -2.21169547e-01,  3.02352718e-01, -2.37873693e-01,
         1.31523660e+00,  1.57366055e-01, -9.53011688e-01,
        -9.82763709e-01],
       [ 3.28797975e-01, -4.69295318e-01, -1.13038833e+00,
        -8.29025865e-01, -7.90949943e-01, -1.21866670e-01,
    

In [69]:
X_test

array([[ 3.28797975e-01, -4.69295318e-01, -1.13038833e+00,
         1.82583077e-01, -7.90949943e-01, -1.21866670e-01,
        -9.41654571e-01, -1.21468051e+00, -7.98052621e-01,
         1.53892721e-01, -1.25251243e+00, -5.32820983e-01,
        -3.52886991e-01, -8.64382552e-01,  7.48816868e-03,
        -1.10945866e+00, -3.36969687e-01, -2.88348910e-01,
        -9.15570870e-01, -2.62960216e-01,  8.85740275e-01,
         1.05519283e+00],
       [ 3.28797975e-01, -4.69295318e-01,  8.84651737e-01,
         1.19419202e+00,  9.33994082e-01, -1.21866670e-01,
         9.56109082e-01,  1.11729520e+00,  2.76731186e-01,
         1.53892721e-01,  1.14636922e+00,  1.63727772e+00,
         1.50203181e+00,  8.20699586e-01, -7.60049121e-01,
        -2.21169547e-01,  3.02352718e-01, -2.37873693e-01,
         1.31523660e+00,  1.57366055e-01, -9.53011688e-01,
        -9.82763709e-01],
       [ 3.28797975e-01, -4.69295318e-01, -1.13038833e+00,
        -8.29025865e-01, -7.90949943e-01, -1.21866670e-01,
    

In [70]:
y_train

array([[ 5.23667906e-01],
       [ 2.62346446e+00],
       [ 2.21259057e-01],
       [-2.53184038e-01],
       [-7.11189142e-01],
       [-7.11189142e-01],
       [ 1.99801832e-01],
       [-1.98599868e-01],
       [-6.00013109e-01],
       [ 1.32988237e+00],
       [-7.75184376e-01],
       [-6.54848240e-01],
       [-3.36503323e-01],
       [ 4.04837541e-01],
       [ 6.42749233e-01],
       [-3.11407153e-01],
       [ 6.45384331e-01],
       [-4.16183663e-01],
       [-8.84352716e-01],
       [-8.52982503e-01],
       [ 2.80235057e-01],
       [-3.74147578e-01],
       [-6.00013109e-01],
       [-1.79652260e-01],
       [ 2.78930666e-02],
       [-6.38410249e-01],
       [-8.76070979e-01],
       [-5.64502028e-01],
       [-6.62251610e-01],
       [-7.38042044e-01],
       [-6.62753534e-01],
       [-9.01167150e-01],
       [-7.80956495e-01],
       [-7.71796393e-01],
       [ 4.54653439e-01],
       [-7.24992036e-01],
       [-1.72750813e-01],
       [-7.29509346e-01],
       [ 7.3

In [71]:
y_test

array([[-0.81333055],
       [ 0.31035046],
       [ 0.24761004],
       [-1.01962107],
       [-0.41179183],
       [-0.26071289],
       [-0.98975663],
       [-0.67492518],
       [ 0.49217221],
       [-0.84670846],
       [ 0.9653605 ],
       [ 2.27418851],
       [-0.29258503],
       [ 0.63584779],
       [-0.54712293],
       [-0.41254472],
       [-0.49962843],
       [ 0.70812476],
       [-0.67530162],
       [-0.85185318],
       [-0.41630914],
       [ 0.28901872],
       [-0.42433992],
       [-0.21679459],
       [ 0.34146971],
       [-1.02376194],
       [-0.79538679],
       [ 0.42892986],
       [-0.61720399],
       [-0.97595374],
       [-0.66526315],
       [-0.12381328],
       [ 1.09686443],
       [-0.54317028],
       [-0.80655459],
       [ 3.5182684 ],
       [-0.21102247],
       [ 0.6115045 ],
       [-0.86578155],
       [ 4.03085767],
       [-0.54712293]])

Implementing SVR Machine Learning Model

In [72]:
from sklearn.svm import SVR
model = SVR(kernel='rbf')
model.fit(X_train,y_train.ravel())

SVR()

Predicting the Test Results

In [74]:
y_pred = scy.inverse_transform([model.predict(X_test)])
print(y_pred)

[[ 5864.0709342  15894.89104632 13723.79988087 12428.06952436
  10081.33173037 12024.59624331  6364.79718174  8744.03575621
  17257.06844924  7033.37805416 18196.14670562 21578.05090452
  12850.7030834  13163.74579704  6698.8095787  11516.12910952
  12142.61226698 17866.46017061  8367.96914654  6046.60463196
  10004.24461561 14785.28265947 12065.1093976  11872.26838525
  17643.15400491  8836.36870898  6795.05458084 15282.81388224
   6562.46461281  7083.0726666   9885.01834229 11451.10911878
  15238.54982454 11024.06262377  6685.09881093 26768.89259461
  11382.13310025 15041.00507887  6609.51908279 31054.75082047
   6528.66115673]]
